#!/usr/bin/env bash
# Publish PR screenshots to the `screenshots` orphan branch and update the
# sticky comment on the PR.
#
# Required env: GH_TOKEN, REPO (owner/name), PR_NUMBER, HEAD_SHA.
# Reads PNGs from tests/Browser/Screenshots/.

set -euo pipefail

: "${GH_TOKEN:?missing}"
: "${REPO:?missing}"
: "${PR_NUMBER:?missing}"
: "${HEAD_SHA:?missing}"

SHOT_DIR="tests/Browser/Screenshots"
COMMENT_MARKER="<!-- screenshots-bot:v1 -->"
BRANCH="screenshots"
SUBPATH="pr-${PR_NUMBER}/${HEAD_SHA}"

if [ ! -d "${SHOT_DIR}" ] || [ -z "$(find "${SHOT_DIR}" -maxdepth 1 -name '*.png' -print -quit)" ]; then
    echo "No screenshots produced — skipping publish."
    exit 0
fi

# Stage PNGs in a temp area before clobbering the screenshots worktree.
STAGE="$(mktemp -d)"
cp "${SHOT_DIR}"/*.png "${STAGE}/"

WORK="$(mktemp -d)"
git -C "${WORK}" init -q -b "${BRANCH}"
git -C "${WORK}" config user.name "github-actions[bot]"
git -C "${WORK}" config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git -C "${WORK}" remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"

if git -C "${WORK}" fetch --depth=1 origin "${BRANCH}" 2>/dev/null; then
    git -C "${WORK}" reset --hard "origin/${BRANCH}"
else
    # Branch doesn't exist yet — start clean as an orphan.
    echo "# Screenshots" > "${WORK}/README.md"
    echo "" >> "${WORK}/README.md"
    echo "Auto-generated by .github/workflows/screenshots.yml. Each PR commit lands under \`pr-<n>/<sha>/\`." >> "${WORK}/README.md"
    git -C "${WORK}" add README.md
    git -C "${WORK}" commit -q -m "Initialize screenshots branch"
fi

mkdir -p "${WORK}/${SUBPATH}"
cp "${STAGE}"/*.png "${WORK}/${SUBPATH}/"
git -C "${WORK}" add "${SUBPATH}"

if git -C "${WORK}" diff --cached --quiet; then
    echo "Screenshots unchanged for this commit."
else
    git -C "${WORK}" commit -q -m "PR #${PR_NUMBER} @ ${HEAD_SHA:0:7}"
    # Two PRs can race for the `screenshots` branch tip. Disjoint pr-*/sha/
    # paths rebase cleanly, so we retry up to 5x on push rejection.
    attempt=0
    until git -C "${WORK}" push -q origin "HEAD:${BRANCH}"; do
        attempt=$((attempt + 1))
        if [ "${attempt}" -ge 5 ]; then
            echo "Push failed after ${attempt} attempts." >&2
            exit 1
        fi
        echo "Push rejected, refetching and rebasing (attempt ${attempt}/5)..." >&2
        git -C "${WORK}" fetch origin "${BRANCH}"
        git -C "${WORK}" rebase "origin/${BRANCH}"
        sleep $((attempt * 2))
    done
fi

# Build the comment body.
BODY_FILE="$(mktemp)"
{
    echo "${COMMENT_MARKER}"
    echo "## Screenshots"
    echo ""
    echo "_Updated for [\`${HEAD_SHA:0:7}\`](https://github.com/${REPO}/pull/${PR_NUMBER}/commits/${HEAD_SHA})._"
    echo ""
    for png in $(ls "${STAGE}" | sort); do
        name="${png%.png}"
        url="https://raw.githubusercontent.com/${REPO}/${BRANCH}/${SUBPATH}/${png}"
        echo "<details open><summary><code>${name}</code></summary>"
        echo ""
        echo "<img src=\"${url}\" alt=\"${name}\" />"
        echo ""
        echo "</details>"
        echo ""
    done
} > "${BODY_FILE}"

# Find an existing sticky comment by marker.
existing_id="$(
    curl -fsSL \
        -H "Authorization: Bearer ${GH_TOKEN}" \
        -H "Accept: application/vnd.github+json" \
        "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments?per_page=100" \
    | jq -r --arg marker "${COMMENT_MARKER}" \
        '[.[] | select(.body | startswith($marker))][0].id // empty'
)"

# GitHub's API expects a JSON body with a "body" key. jq builds it from the file.
payload="$(jq -Rs '{body: .}' < "${BODY_FILE}")"

if [ -n "${existing_id}" ]; then
    echo "Updating sticky comment ${existing_id}"
    curl -fsSL -X PATCH \
        -H "Authorization: Bearer ${GH_TOKEN}" \
        -H "Accept: application/vnd.github+json" \
        -d "${payload}" \
        "https://api.github.com/repos/${REPO}/issues/comments/${existing_id}" >/dev/null
else
    echo "Creating sticky comment"
    curl -fsSL -X POST \
        -H "Authorization: Bearer ${GH_TOKEN}" \
        -H "Accept: application/vnd.github+json" \
        -d "${payload}" \
        "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments" >/dev/null
fi

echo "Done."
